### PR TITLE
Fix ascii_only returning something other than letters, numbers, or spaces

### LINKED ISSUE #17: Slugify-ing foreign characters?
Calling:
slugify.slufigy("Ставки земельного налога в городах Свердловской области в 2014 году") 

generates this slug:
stavki-zemel'nogo-naloga-v-gorodakh-sverdlovskoi-oblasti-v-2014-godu

The single quote char was unexpected.  Is there a way to force the slugs to only contain alphanumeric or hyphen characters, even when using a foreign language?

### PR DESCRIPTION
**Pull request by nitely**
fixes #17

### CODE REVIEW

**Comment by nitely** [comment]
why doesn't travis run the tests?

**Comment by davedash** [comment]
Good question... I'll check later

**Comment by jezdez** [comment]
@nitely Travis was disabled for some reason. Just re-enabled it.

@davedash I've regained access to the repo and will be able to do a PyPI release soon.

**Comment by jezdez** [comment]
Tests running now: https://travis-ci.org/mozilla/unicode-slugify/builds/416957866

**Comment by jezdez** [comment]
Aand they failed. @nitely want to take a look at the test build above?

**Comment by nitely** [comment]
@jezdez sure, I'll fix it in a bit

**Comment by nitely** [comment]
@jezdez tests at #30 should pass now. Thanks for taking care of this :smile:

**Pull request merged**
